arm:
  _target_: mujoco_controllers.models.arms.franka_emika.FER
  relative_robot_mjcf_path: "./mujoco_menagerie/franka_emika_panda/panda_nohand.xml" # relative to scripts directory
  actuator_config:
    type: "motor"
    high_torque_motor:
      ctrlrange: '-87 87'
    low_torque_motor:
      ctrlrange: '-12 12'
    joint_actuator_mapping:
      joint1: "high_torque_motor"
      joint2: "high_torque_motor"
      joint3: "high_torque_motor"
      joint4: "high_torque_motor"
      joint5: "low_torque_motor"
      joint6: "low_torque_motor"
      joint7: "low_torque_motor"
  
  sensor_config:
    type: "jointpos"
    pos_joint1:
      name: pos_joint1 
      joint: joint1
    pos_joint2:
      name: pos_joint2
      joint: joint2
    pos_joint3:
      name: pos_joint3
      joint: joint3
    pos_joint4:
      name: pos_joint4
      joint: joint4
    pos_joint5:
      name: pos_joint5
      joint: joint5
    pos_joint6:
      name: pos_joint6
      joint: joint6
    pos_joint7:
      name: pos_joint7
      joint: joint7

    joint_sensor_mapping:
      pos_joint1: "joint1"
      pos_joint2: "joint2"
      pos_joint3: "joint3"
      pos_joint4: "joint4"
      pos_joint5: "joint5"
      pos_joint6: "joint6"
      pos_joint7: "joint7"

gripper:
  _target_: dm_robotics.moma.models.end_effectors.robot_hands.robotiq_2f85.Robotiq2F85
