controller_params:
  name: diffik
  physics_dt: ${physics_dt}
  control_dt: ${control_dt}

controller:
  _target_: mujoco_controllers.diffik.DiffIK
  _partial_: true
  controller_config: ${robots.arm.controller_config.controller_params}

