min_objects: 1
max_objects: 3
min_object_size: 0.02
max_object_size: 0.03
sample_size: true
sample_colour: true
color_noise: 0.1
shapes:
  #- cube
  #- cylinder
  - rectangle
colours:
  - red
  - green
  - blue
  - yellow
  - magenta
  - cyan
  - grey
