use_simulation: True # whether we are running a simulated or real experiment

initializers:
  workspace:
    min_pose: [0.4, -0.3, 0.4, 0.0, 0.0, -3.14]
    max_pose: [0.65, 0.3, 0.6, 0.0, 0.0, 3.14]

  gripper:
    min_pose: [0.0, -0.0, 0.8, 3.14, 0.0, 0.0]
    max_pose: [0.0, 0.0, 0.8, 3.14, 0.0, 0.0]
