use_simulation: True # whether we are running a simulated or real experiment

initializers:
  workspace:
    min_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    max_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  gripper:
    min_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    max_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
